title: Philip Gant # your name (or website title) here
logo: "/images/IMG_4598 2.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Regulatory Ecosystems Group 
  & Harvard Asia Center
  <br><br>
  <a href="https://www.linkedin.com/in/philip-gant//">Connect on LinkedIn</a> 
  <br><br>
  <a href="https://orcid.org/0000-0002-4394-7558/">Read My Work</a> 
  <br><br>
  <a href="featuring.md">Check Out Stuff Catching My Eye</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-KC79S2WK27 # your Google Analytics tracking ID here
